version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: sqlite:latest
    container_name: sqlite
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
