# Generated by Django 4.1.7 on 2024-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='session_duration',
            field=models.DurationField(default=11),
            preserve_default=False,
        ),
    ]
